# Generated by Django 4.2.16 on 2024-10-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='resolution_days',
            field=models.IntegerField(default=5, verbose_name='Количество рабочих дней на решение'),
        ),
    ]
