# Generated by Django 4.2.16 on 2024-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_category_resolution_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
