# Generated by Django 4.2.16 on 2024-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
