# Generated by Django 5.0.6 on 2024-10-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_application_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'verbose_name': 'База для обучения', 'verbose_name_plural': 'База для обучения'},
        ),
        migrations.AddField(
            model_name='application',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
    ]
